### PR TITLE
ibex added to the design with drc lvs clean

### PR DESCRIPTION
**Pull request by peijunh**
The Ibex RISC-V Core Wrapper instantiates an Ibex RV32 CPU Core, and wraps its data and instruction memory interfaces to TileLink Uncached Light (TL-UL). Now I add the ibex core to OpenLane. I run the whole OpenLane interactive flow without seeing drc, lvs error.

### CODE REVIEW

**Comment by maliberty** [comment]
@donn this looks ok to me but I'll leave it to you to approve.  How can we get it into the regression for OL?

**Comment by donn** [comment]
We'd have to run the flow at least once and get the results then add them to SW_HD.csv.

Until that's done, I can't merge this…

**Comment by peijunh** [comment]
@donn I have already run the flow. should I provide the resulted gds? or provide the log file?

**Comment by donn** [comment]
We have the concept of a “run path” in OpenLane: under the design’s folder, there is `runs`.

Whatever the run that succeeded is, send me its folder.

**Comment by peijunh** [comment]
Attached is the result of a ru
[ibex.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7214767/ibex.tar.gz)
n

**Comment by peijunh** [comment]
The run file is large and cannot be attached directly even after compressed. So I upload it in my github and please go to there to git clone it.

**Comment by donn** [comment]
Thank you, I'll take a look.

**Comment by peijunh** [comment]
@donn @rovinski  Hi, may I ask the status of your review? Thanks.

**Comment by rovinski** [comment]
@peijunh I don't work with OpenLane.

**Pull request closed without merging**
