### PR TITLE
Installation, Quickstart Guide and Sphynx Overhaul

### PR DESCRIPTION
**Pull request by armleo**
+ Documentation changed, README no longer documentation's landing page
+ New installation and quickstart guides created

### CODE REVIEW

**Comment by armleo** [comment]
@vijayank88 Did you test the changes in the RTD? Why change warnings to **warnings**. They are not as eye catching as the red message.

**Comment by vijayank88** [comment]
@armleo 
`note` `warning` should be highlighted from regular format. So user care about information given.

I fixed the broken links of `.html` to `.md`. Is that correct or point the right source files?

I didn't fully completed readthedocs.io review. Only quickstart and installation docs reviewed.

**Comment by armleo** [comment]
> note warning should be highlighted from regular format. 

That is correct. But the docs are not supposed to be viewed with GitHub UI. All of the docs will migrate to .rst + RTD. RST is not supported properly by GitHub.

**Comment by armleo** [comment]
Ready for merge one CI passes.

**Review by donn — APPROVED** [review]
I had to do some copywriting, but otherwise, pretty good. I do expect the remaining markdown files in `docs/` to be converted to `rst` as well, eventually.

**Comment by vijayank88** [comment]
@armleo Can you confirm is the `merge-window-3` latest one or `merge-windows-4` is latest?

**Comment by donn** [comment]
I spent entirely too much time copywriting mw3. You'll have to rebase mw4 and open a new PR.

**Pull request merged**
