### PR TITLE
Documentation Overhaul

### PR DESCRIPTION
**Pull request by armleo**
Live: https://armleo-openlane.readthedocs.io/en/merge-window-4/

Continuation of https://github.com/The-OpenROAD-Project/OpenLane/pull/1259

### CODE REVIEW

**Comment by donn** [comment]
Appears to revert a lot of the changes in #1333. Please rebase.

**Comment by armleo** [comment]
@donn You referring to docs/source/quickstart.rst file only, correct?

**Comment by donn** [comment]
I meant #1337, merged now, sorry. have fun

**Comment by armleo** [comment]
UPD: The pull request is ready to be merged

**Review by donn — APPROVED** [review]

**Pull request merged**
