### PR TITLE
Update PDN Configurations

### LINKED ISSUE #1037: OpenLane now fails on PDN with latest OpenROAD changes
OpenLANE fails on PDN step due to OpenROAD [pdn: convert to c++ #1749](https://github.com/The-OpenROAD-Project/OpenROAD/pull/1749) .

Error [with a reproductible](https://github.com/The-OpenROAD-Project/OpenLane/files/8456577/pdn-issue.tar.gz) step:
```
$ openlane-flow.tcl -design spm
OpenLane 2022.03.31.02.35.19-20220401.0.git2f276c62.fc37
{...}
[STEP 6]
[INFO]: Generating PDN...
[ERROR]: during executing openroad script /usr/share/openlane/scripts/openroad/pdn.tcl
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
[INFO ODB-0130]     Created 36 pins.
[INFO ODB-0131]     Created 478 components and 2698 component-terminals.
[INFO ODB-0133]     Created 352 nets and 984 connections.
[INFO ODB-0134] Finished DEF file: /home/cbalint/rpmbuild/SPECS/MAIN/RUN_2022.04.09_11.42.16/results/floorplan/spm.def
[WARNING PDN-1024] -verbose has been deprecated.
[WARNING PDN-1000] Using legacy PDNGEN.
Consider using "convert_pdn_config /usr/share/openlane/scripts/openroad/pdn_cfg.tcl" to convert the legacy configuration.
[ERROR PDN-0175] Pitch 28.8270 is too small for, must be atleast 28.8300
Error: pdn_cfg.tcl, 39 PDN-0175
{...}
```
OpenROAD version:
```
$ openroad -version
2.0-20220407.git34e0ea38.fc37 
```

---

All [openlane builds fails](https://copr.fedorainfracloud.org/coprs/rezso/VLSI/build/4123317) at post-build regression tests ```%check``` stage. 
Unsure what possible solution would be beyond just having ```convert_pdn_config```.

Cc @arlpetergadfort , @maliberty 

---

FYI, there is a little flow with the native .rpm repo usage: https://gist.github.com/cbalint13/1de29fbe77e8dedddd3861b5f49a1835

Thanks,
~cristian.

### PR DESCRIPTION
**Pull request by maliberty**
Update pdn_cfg.tcl to use only commands supported by the new pdngen

The prior code was a mix of new commands and old tcl vars that are no
longer supported by the new pdngen.  I find the old setup confusing
so this is my best guess at a correct replacement.

---
Notes from maintainer:

Resolves #1037.

Will be merged after mpw-6 is tagged so we don't break all the caravel scripts.

### CODE REVIEW

**Review by donn — CHANGES_REQUESTED** [review]
Like, every design broke in CI.

**Comment by maliberty** [comment]
@ravi-varadarajan this could be a public RTL-MP test case once its ready.  Currently it has a fixed macro placement due to poor TMP results.

**Comment by maliberty** [comment]
@antonblanchard how much does the cts tuning get you?

**Comment by maliberty** [comment]
I don't know if there is any more extended testing you want to do but the CI checks are green.

**Comment by donn** [comment]
LGTM- We're going to hold off on the merge until we tag for mpw-6 because of all the pdngen scripts that will be broken in caravel, though

**Comment by maliberty** [comment]
@donn I'll leave it to you to merge when you are ready

**Comment by donn** [comment]
Wait why did you close this and delete the branch?

**Comment by maliberty** [comment]
I realized it had other changes in it.

**Comment by maliberty** [comment]
Also I saw that you were fixing it so  stopped.

**Comment by maliberty** [comment]
Ack - wrong PR but the reopen button is grayed out for some reason.

**Comment by maliberty** [comment]
I'll have to recreate this one.

**Pull request closed without merging**
