### PR TITLE
Fix multiple synthesis libraries

### PR DESCRIPTION
**Pull request by Manarabdelaty**
Fixes https://github.com/The-OpenROAD-Project/OpenLane/issues/683

### CODE REVIEW

**Review by donn — DISMISSED** [review]

**Review by donn — DISMISSED** [review]

**Review by donn — APPROVED** [review]

**Comment by vijayank88** [comment]
@donn  
is this PR tested against designs/spm/config.tcl by setting below variable?
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hvl"

Still I'm facing error as below
```
[INFO ODB-0222] Reading LEF file: /openlane/designs/spm/runs/def_hvllib/tmp/merged_unpadded.lef
[INFO ODB-0223]     Created 13 technology layers
[INFO ODB-0224]     Created 25 technology vias
[INFO ODB-0225]     Created 69 library cells
[INFO ODB-0226] Finished LEF file:  /openlane/designs/spm/runs/def_hvllib/tmp/merged_unpadded.lef
Error: sta.tcl, 38 cannot read file  /home/vijayan/OPENLANE_FLOW/Aug15_2021_OpenLane/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hvl/lib/sky130_fd_sc_hvl__tt_025C_3v30.lib /home/vijayan/OPENLANE_FLOW/Aug15_2021_OpenLane/OpenLane/pdks/sky130A/libs.ref/sky130_fd_sc_hvl/lib/sky130_fd_sc_hvl__tt_025C_3v30_lv1v80.lib .
[ERROR]: during executing: "openroad -exit /openlane/scripts/openroad/sta.tcl |& tee >&@stdout /openlane/designs/spm/runs/def_hvllib/logs/synthesis/1-opensta"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child process exited abnormally
```

**Comment by donn** [comment]
No. If the issue persists please reopen the issue so we can investigate.

**Comment by hpretl** [comment]
If I hack `scripts/openroad/sta.tcl` in this way, then it works (and crashes later at step 7, uff):

```
read_liberty "/usr/local/share/pdk/sky130A/libs.ref/sky130_fd_sc_hvl/lib/sky130_fd_sc_hvl__tt_025C_3v30.lib"
read_liberty "/usr/local/share/pdk/sky130A/libs.ref/sky130_fd_sc_hvl/lib/sky130_fd_sc_hvl__tt_025C_3v30_lv1v80.lib"
#read_liberty $::env(LIB_SYNTH_COMPLETE)
```

So yes, the `read_liberty` function does not work when multiple libs are passed via `LIB_SYNTH_COMPLETE`, which happens when using the HVL lib.

**Comment by hpretl** [comment]
> and crashes later at step 7, uff

BTW, then throwing this error:

```
[ERROR STA-0026] /openlane/designs/audiodac/runs/RUN_2021.11.23_15.13.33/tmp/trimmed.lib line 31779, syntax error, unexpected KEYWORD, expecting $end.
Error: replace.tcl, 52 STA-0026
[ERROR]: during executing: "openroad -exit /openlane/scripts/openroad/replace.tcl |& tee >&@stdout /openlane/designs/audiodac/runs/RUN_2021.11.23_15.13.33/logs/placement/7-replace.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child process exited abnormally

[ERROR]: Please check openroad  log file
[ERROR]: Dumping to /openlane/designs/audiodac/runs/RUN_2021.11.23_15.13.33/error.log
```

**Comment by donn** [comment]
Ah, thanks for the diagnostic help.

**Pull request merged**
