### PR TITLE
Repair max slew and max capacitance violations at all resizer stages

### PR DESCRIPTION
**Pull request by antonblanchard**
Placement and global routing could create new max slew and max capacitance
violations, so call repair_design at all resizer stages.

---
[ci ets]

### CODE REVIEW

**Comment by maliberty** [comment]
repair_design does not operate on clock nets so at least that much is ok.

**Comment by maliberty** [comment]
@donn this would need CI to establish if it is beneficial in general.

**Comment by donn** [comment]
@maliberty I'll run the full suite.

**Comment by donn** [comment]
I'd actually say that's an improvement.

**Review by donn — APPROVED** [review]

**Pull request merged**
