### PR TITLE
Fix global placement cell padding

### PR DESCRIPTION
**Pull request by antonblanchard**
We were using the detailed placement interface.

### CODE REVIEW

**Comment by antonblanchard** [comment]
This is going to require many designs to update `PL_TARGET_DENSITY`. I'm not sure if there is a way to avoid it though.

**Comment by donn** [comment]
What would be the damage on waiting on this PR for a bit? It looks like it's gonna need a lot more work and I get to go on vacation soonish

**Comment by antonblanchard** [comment]
I think it can wait, since it is going to break quite a few things.

**Comment by vijayank88** [comment]
@donn 
Can you please check this PR? 
Its need to be merged ASAP.

**Comment by donn** [comment]
@vijayank88 
> Can you please check this PR?
> Its need to be merged ASAP.

Given that it breaks half the designs and I still have not had it adequately explain to me what the urgency is I wouldn't hold my breath.

**Comment by antonblanchard** [comment]
We are applying zero padding during global placement, regardless of the setting. The fact detailed placement works at all with a non zero padding is just luck.

**Comment by donn** [comment]
When did `set_placement_padding -global -right $::env(CELL_PAD)` stop working?

**Comment by antonblanchard** [comment]
Global placement padding seems to have been added back in April 2020 via the `-pad_left` and `-pad_right` options:

https://github.com/The-OpenROAD-Project/RePlAce/commit/4c3e2954a4554b3ae110793067ca4e94b3de7860

Seems a lot like OpenROAD has been broken since day 0.

**Comment by antonblanchard** [comment]
> When did `set_placement_padding -global -right $::env(CELL_PAD)` stop working?

`-global` in this context means all instances in detailed placement, not global placement doesn't it?

**Comment by donn** [comment]
> -global in this context means all instances in detailed placement, not global placement doesn't it?

That's amazing.

**Comment by donn** [comment]
Continued in #1226…

**Pull request closed without merging**
