### PR TITLE
Issue regression flow and apply_def_template.py fix

### PR DESCRIPTION
**Pull request by armleo**
This commit adds -run_hooks flag which allows to run python scripts after design was ran. Example design was added. All designs should pass after this pull request, except new def_test design should be added but not run. If you run this, it should not pass, as the def flow has issues, that should be soon resolved. See #881

Fixes apply_def_template.py crashing see #869

### CODE REVIEW

**Review by donn — APPROVED** [review]
Looks good, thank you so much for your contribution. Will merge when CI clears.

**Comment by maliberty** [comment]
@donn this partially reverted my changes and should not have been approved.  See flow.tcl

**Comment by armleo** [comment]
This is correct, will fix this as soon as I will get to this.

**Comment by maliberty** [comment]
Thanks, I've fixed it with another PR

**Comment by armleo** [comment]
I merged with wrong commit. This was my first time doing a PR, so I messed up.

**Comment by maliberty** [comment]
> I merged with wrong commit. This was my first time doing a PR, so I messed up.

No worries it wasn't hard to fix

**Pull request merged**
