### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by wsoyinka**
Change command from pull-if-doesnt-exist to the correct pull_if_doesnt_exist expected by util.py

### CODE REVIEW

**Comment by kareefardi** [comment]
According to click's [docs](https://click.palletsprojects.com/en/8.0.x/options/):
> To get the Python argument name, the chosen name is converted to lower case, up to two dashes are removed as the prefix, and other dashes are converted to underscores.

Furthermore, that's the output I got from running the patched version:

```
❯ python3 ./utils.py pull_if_doesnt_exist 
Usage: utils.py [OPTIONS] COMMAND [ARGS]...
Try "utils.py --help" for help.

Error: No such command "pull_if_doesnt_exist".
```

**Comment by wsoyinka** [comment]
This is the relevant line from utils.py :

***
def pull_if_doesnt_exist(repository, operating_system, tool):
***

https://github.com/The-OpenROAD-Project/OpenLane/blob/58f206fb30a7c01d7e11b0e7a13fdfc4a5e4d09b/docker/utils.py#L37

**Comment by donn** [comment]
The command name does not match the python function name. Please try things out before submitting pull requests.

**Comment by wsoyinka** [comment]
@donn  :

You are exactly correct. 

The command does NOT match the python function name.  That is what this patch is trying to fix. That is the reason why this PR was made.

The python function name in utils.py is:

pull_if_doesnt_exist

The line in the Makefile is :

python3 **./utils.py pull-if-doesnt-exist** --repository $(TOOL_REPOSITORY) --os $(OS_NAME) $*

The patch was tested. It was tested before submitting this PR.

The fix is to either:
a) change the function name in utils.py  to pull-if-doesnt-exist
or
b) change the command name in the Makefile to pull_if_doesnt_exist

I submitted a patch doing (b)

Perhaps I am missing some other detail and you can point it out to me ?

**Comment by wsoyinka** [comment]
@donn , @kareefardi 

Steps to reproduce:

1)
```
 #  git clone https://github.com/The-OpenROAD-Project/OpenLane.git
```

2)  
```
# cd OpenLane/docker/
```

3)
```
  # git describe --tags
2022.02.19_02.27.52
```

4)
```
 # git branch -v
* master 58f206f Update Magic, Open_PDKS (#917)
```

5) 
```
# make merge
.....<OUTPUT TRUNCATED>...

Removing intermediate container 4d04e89aa16a
 ---> 477a09e3455b
Successfully built 477a09e3455b
Successfully tagged openlane-run-base:latest
rm -f tar/cugr.tar.gz && echo "Deleted existing tar/cugr.tar.gz"
Deleted existing tar/cugr.tar.gz
mkdir -p tar
python3 ./utils.py pull-if-doesnt-exist --repository efabless/openlane-tools --os centos-7 cugr
Usage: utils.py [OPTIONS] COMMAND [ARGS]...

Error: No such command "pull-if-doesnt-exist".
Makefile:61: recipe for target 'tar/cugr.tar.gz' failed
make: *** [tar/cugr.tar.gz] Error 2

```

6) 
```
 # grep pull  Makefile
python3 ./utils.py pull-if-doesnt-exist --repository $(TOOL_REPOSITORY) --os $(OS_NAME) $*
```

7) 
```
# grep -n  "def pull" utils.py
37:def pull_if_doesnt_exist(repository, operating_system, tool):
```

8) 
```
# grep  -n  pull  Makefile
63:	python3 ./utils.py pull-if-doesnt-exist --repository $(TOOL_REPOSITORY) --os $(OS_NAME) $*
```

**Comment by wsoyinka** [comment]
@donn  -   I've helped to update your official list of requirements to include the minimum version of click needed (>=7.0). Hopefully it'll work better for others.

**Pull request closed without merging**
