### PR TITLE
Issue regression flow

### PR DESCRIPTION
**Pull request by armleo**
See: https://github.com/The-OpenROAD-Project/OpenLane/issues/881

This commit adds -run_hooks flag which allows to run python scripts after design was ran. Example design was added. All designs should pass after this pull request, except new def_test design should be added but not run. If you run this, it should not pass, as the def flow has issues, that should be soon resolved.

### CODE REVIEW

**Comment by donn** [comment]
Looks okay- though it will fail Python linting. We require black formatting and flake8 to pass.

**Comment by armleo** [comment]
Will update the formatting asap

**Comment by donn** [comment]
Wait, why? If you don't want to resolve the conflicts just tell me and I'll do it

**Comment by armleo** [comment]
@donn I created one branch with all changes and created a merged pull request. This is my first time contributing using Pull Requests, I didn't know how to do this properly.

**Comment by donn** [comment]
Ah, that makes sense.

**Pull request closed without merging**
