### PR TITLE
Update OpenROAD image

### PR DESCRIPTION
**Pull request by osamahammad21**
This PR includes updates to dockerimage of openroad and necessary updates on scripts. This passes fastest_test_set. It is a draft PR and I am currently working on testing and documenting the changes.

### CODE REVIEW

**Comment by osamahammad21** [comment]
@donn Here are my updates on openlane. I am still working on analyzing the metrics before making it ready for review.

**Comment by donn** [comment]
I merged them into #433… couple notes, though:

- The Open_PDKs changes will need to be upstreamed before we can merge into OpenLane. Is this change breaking?
- I just use a new_tracks.py script to convert the tracks file into make_tracks.
- I haven't updated the actual docker image yet (testing using the local installer, as it turns out development goes a lot faster when you don't have to build an image every time :) )

**Comment by osamahammad21** [comment]
I have a [PR](https://github.com/RTimothyEdwards/open_pdks/pull/131) for the OpenPDK and waiting for it to be merged

**Comment by donn** [comment]
Work migrated to #433.

**Pull request closed without merging**
