### PR TITLE
Use `open_pdks` upstream 

### PR DESCRIPTION
**Pull request by kareefardi**
Signed-off-by: Kareem Farid <kareefardi@users.noreply.github.com>

### CODE REVIEW

**Comment by kareefardi** [comment]
This PR is also done to trigger the CI

**Comment by donn** [comment]
Volare needs to be updated first

**Comment by maliberty** [comment]
@donn I believe @proppy already opened a volare PR to do the same.

**Comment by donn** [comment]
For posterity: related PRs:

https://github.com/efabless/volare/pull/22
https://github.com/efabless/volare/pull/23

**Review by donn — APPROVED** [review]

**Pull request merged**
