### PR TITLE
Added missing list braces

### PR DESCRIPTION
**Pull request by Syndace**
Fun little bug that makes the code fail when MACRO_BLOCKAGES_LAYER contains an even number of elements LOL

### CODE REVIEW

**Review by donn — APPROVED** [review]
Ah, well, our decision to use Tcl is paying off dividends I see. Thank you.

**Comment by donn** [comment]
The lint issue is likely because your changes are based on an older version of OpenLane. I'll just ignore it for the merge.

**Review by donn — DISMISSED** [review]

**Comment by Syndace** [comment]
The changes are based on the most recent commit of the master branch, so an older version can't be the cause for linting issues. I assume one of the Python linters that your pipeline uses has been updated in the last two days and complains about something that was okay in the previous version, since you are not pinning the versions of the linters as far as I can see.

**Comment by donn** [comment]
wow good start to the week

**Review by donn — DISMISSED** [review]
Thanks for noticing the linter thing. I'll update black sometime a little less weekend.

**Review by donn — APPROVED** [review]

**Comment by Syndace** [comment]
(may I suggest doing `python3 -m pip install -r requirements_dev.txt` instead, single source of thruth and stuff, sorry if I'm annoying :D)

**Comment by donn** [comment]
@Syndace I did have a requirements_lint.txt at some point but it got lost in merge hell at some point. I'll bring it back when I update black.

**Pull request merged**
