### PR TITLE
Tool Updater Overhaul

### PR DESCRIPTION
**Pull request by donn**
This changes the CI in some aspects:

- The tool update flow is now a separate GitHub Action from the CI. Resulting branches are stored in https://github.com/openlane-bot/OpenLane. One PR is created and is constantly updated by Openlane Bot until merged, instead of the nightly CID-latest-whatever email spam.
- Some CI scripts can now be run locally by mocking the gh object
- Tags now created for any new commits found during a day, not just >=2
- Documentation updates

**This is a CI-only change with no effect on OpenLane code.**

### CODE REVIEW

**Comment by donn** [comment]
@tspyrou @maliberty I need access to OpenLane secrets.

**Comment by maliberty** [comment]
Mohamed Shalan and Jeff DiCorpo both have admin access to the OL repository
and should be able to take care of your needs.  I don't want to change
permissions on your repo.

Matt

**Comment by donn** [comment]
Muy bien.

**Review by Manarabdelaty — APPROVED** [review]

**Comment by donn** [comment]
Donn didn't dismiss anything!! Donn pushed a fix!!

**Review by Manarabdelaty — APPROVED** [review]

**Review by jeffdi — APPROVED** [review]

**Pull request merged**
